export const categories = [
  { id: 1, name: "Confectionery", icon: "🧁", price: 3.99, description: "Sweet confectionery" },
  { id: 2, name: "Home Essentials", icon: "🏠", price: 15.99, description: "Household items" },
  { id: 3, name: "Alcoholic Beverages", icon: "🍺", price: 5.99, description: "Cold beer" },
  { id: 4, name: "Payment Services", icon: "💳", price: 0, description: "Payment services" },
  { id: 5, name: "Dairy Products", icon: "🥛", price: 4.49, description: "Fresh dairy products" },
  { id: 6, name: "Grocery Items", icon: "🛒", price: 12.99, description: "Grocery items" },
  { id: 7, name: "Soft Drinks", icon: "🥤", price: 2.99, description: "Soft drinks" },
  { id: 8, name: "Pet Supplies", icon: "🐾", price: 19.99, description: "Pet food and treats" },
  { id: 9, name: "Frozen Foods", icon: "❄️", price: 8.99, description: "Frozen foods" },
  { id: 10, name: "Instant Meals", icon: "⚡", price: 6.99, description: "Instant meals" },
  { id: 11, name: "Shopping Bags", icon: "👜", price: 1.99, description: "Shopping bags" },
  { id: 12, name: "Ice Cream", icon: "🍦", price: 4.99, description: "Ice cream treats" },
  { id: 13, name: "Cream Filled Eggs", icon: "🥚", price: 2.49, description: "Cream filled eggs" },
  { id: 14, name: "Magazines & Newspapers", icon: "📰", price: 7.99, description: "Magazines & newspapers" },
  { id: 15, name: "Home Essentials", icon: "🏠", price: 15.99, description: "Household items" },
  { id: 16, name: "Alcoholic Beverages", icon: "🍺", price: 5.99, description: "Cold beer" },
  { id: 17, name: "Payment Services", icon: "💳", price: 0, description: "Payment services" },
  { id: 18, name: "Dairy Products", icon: "🥛", price: 4.49, description: "Fresh dairy products" },
  { id: 19, name: "Grocery Items", icon: "🛒", price: 12.99, description: "Grocery items" },
  { id: 20, name: "Soft Drinks", icon: "🥤", price: 2.99, description: "Soft drinks" },
  { id: 21, name: "Pet Supplies", icon: "🐾", price: 19.99, description: "Pet food and treats" },
  { id: 22, name: "Frozen Foods", icon: "❄️", price: 8.99, description: "Frozen foods" },
  { id: 23, name: "Instant Meals", icon: "⚡", price: 6.99, description: "Instant meals" },
  { id: 24, name: "Shopping Bags", icon: "👜", price: 1.99, description: "Shopping bags" },
  { id: 25, name: "Frozen Foods", icon: "❄️", price: 8.99, description: "Frozen foods" },
  { id: 26, name: "Instant Meals", icon: "⚡", price: 6.99, description: "Instant meals" },
  { id: 27, name: "Shopping Bags", icon: "👜", price: 1.99, description: "Shopping bags" },
  { id: 28, name: "Ice Cream", icon: "🍦", price: 4.99, description: "Ice cream treats" },
  { id: 29, name: "Cream Filled Eggs", icon: "🥚", price: 2.49, description: "Cream filled eggs" },
  { id: 30, name: "Magazines & Newspapers", icon: "📰", price: 7.99, description: "Magazines & newspapers" },
  { id: 31, name: "Home Essentials", icon: "🏠", price: 15.99, description: "Household items" },
  { id: 32, name: "Alcoholic Beverages", icon: "🍺", price: 5.99, description: "Cold beer" },
  { id: 33, name: "Payment Services", icon: "💳", price: 0, description: "Payment services" },
  { id: 34, name: "Dairy Products", icon: "🥛", price: 4.49, description: "Fresh dairy products" },
];

export const quickAccess = [
  { id: 1, name: "Quick 1", icon: "⭐" },
  { id: 2, name: "Quick 2", icon: "⚡" },
  { id: 3, name: "Quick 3", icon: "🎯" },
  { id: 4, name: "Quick 4", icon: "🔥" },
  { id: 5, name: "Quick 5", icon: "💫" },
  { id: 6, name: "Quick 6", icon: "✨" },
  { id: 7, name: "Quick 7", icon: "🌟" },
  { id: 8, name: "Quick 8", icon: "💥" },
  { id: 9, name: "Quick 9", icon: "⚡" },
  { id: 10, name: "Quick 10", icon: "🎯" },
  { id: 11, name: "Quick 11", icon: "🔥" },
  { id: 12, name: "Quick 12", icon: "💫" },
  { id: 13, name: "Quick 13", icon: "✨" },
  { id: 14, name: "Quick 14", icon: "🌟" }
];